services:
  metad0:
    image: vesoft/nebula-metad:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=metad0
      - --ws_ip=metad0
      - --port=45500
      - --ws_http_port=11000
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=+08:00
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad0:11000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 45500
      - 11000
      - 11002
    volumes:
      - ./secrets:/secrets
      - ./data/meta0:/data/meta
      - ./logs/meta0:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  metad1:
    image: vesoft/nebula-metad:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=metad1
      - --ws_ip=metad1
      - --port=45500
      - --ws_http_port=11000
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=+08:00
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad1:11000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 45500
      - 11000
      - 11002
    volumes:
      - ./secrets:/secrets
      - ./data/meta1:/data/meta
      - ./logs/meta1:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  metad2:
    image: vesoft/nebula-metad:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=metad2
      - --ws_ip=metad2
      - --port=45500
      - --ws_http_port=11000
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=+08:00
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad2:11000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 45500
      - 11000
      - 11002
    volumes:
      - ./secrets:/secrets
      - ./data/meta2:/data/meta
      - ./logs/meta2:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged0:
    image: vesoft/nebula-storaged:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=storaged0
      - --ws_ip=storaged0
      - --port=44500
      - --ws_http_port=12000
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=+08:00
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged0:12000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 44500
      - 12000
      - 12002
    volumes:
      - ./secrets:/secrets
      - ./data/storage0:/data/storage
      - ./logs/storage0:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged1:
    image: vesoft/nebula-storaged:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=storaged1
      - --ws_ip=storaged1
      - --port=44500
      - --ws_http_port=12000
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=+08:00
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged1:12000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 44500
      - 12000
      - 12002
    volumes:
      - ./secrets:/secrets
      - ./data/storage1:/data/storage
      - ./logs/storage1:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged2:
    image: vesoft/nebula-storaged:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=storaged2
      - --ws_ip=storaged2
      - --port=44500
      - --ws_http_port=12000
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=+08:00
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged2:12000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 44500
      - 12000
      - 12002
    volumes:
      - ./secrets:/secrets
      - ./data/storage2:/data/storage
      - ./logs/storage2:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd0:
    image: vesoft/nebula-graphd:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --port=3699
      - --ws_ip=graphd0
      - --ws_http_port=13000
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --enable_authorize=true
      - --timezone_name=+08:00
      - --system_memory_high_watermark_ratio=0.99
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd0:13000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "3699:3699"
      - 13000
      - 13002
    volumes:
      - ./secrets:/secrets
      - ./logs/graph0:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd1:
    image: vesoft/nebula-graphd:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --port=3699
      - --ws_ip=graphd1
      - --ws_http_port=13000
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --enable_authorize=true
      - --timezone_name=+08:00
      - --system_memory_high_watermark_ratio=0.99
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd1:13000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "3700:3699"
      - 13000
      - 13002
    volumes:
      - ./secrets:/secrets
      - ./logs/graph1:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd2:
    image: vesoft/nebula-graphd:v3
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --port=3699
      - --ws_ip=graphd2
      - --ws_http_port=13000
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --enable_authorize=true
      - --timezone_name=+08:00
      - --system_memory_high_watermark_ratio=0.99
      - --heartbeat_interval_secs=1
      # ssl
      - --ca_path=${ca_path}
      - --cert_path=${cert_path}
      - --key_path=${key_path}
      - --enable_ssl=${enable_ssl}


    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd2:13000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "3701:3699"
      - 13000
      - 13002
    volumes:
      - ./secrets:/secrets
      - ./logs/graph2:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  console:
    image: vesoft/nebula-console:nightly
    entrypoint: ""
    command: 
      - sh
      - -c
      - |
        for i in `seq 1 60`;do
          echo "Adding hosts..."
          var=`nebula-console -addr graphd0 -port 3699 -u root -p nebula -enable_ssl=true \
            -ssl_root_ca_path /secrets/root.crt \
            -ssl_cert_path /secrets/client.crt \
            -ssl_private_key_path /secrets/client.key \
            --ssl_insecure_skip_verify=true \
            -e 'ADD HOSTS "storaged0":44500,"storaged1":44500,"storaged2":44500'`;
          if [[ $$? == 0 ]];then
            echo "Hosts added successfully"
            sleep 2;
            nebula-console -addr graphd0 -port 3699 -u root -p nebula \
              -enable_ssl=true \
              -ssl_root_ca_path /secrets/root.crt \
              -ssl_cert_path /secrets/client.crt \
              -ssl_private_key_path /secrets/client.key \
              --ssl_insecure_skip_verify=true \
              -e 'CREATE SPACE session_pool(partition_num=4, replica_factor=1, vid_type = FIXED_STRING(30))'
            break;
          fi;
          sleep 1;
          echo "retry to add hosts.";
        done && tail -f /dev/null;
    volumes:
      - ./secrets:/secrets
    depends_on:
      - graphd0
    networks:
      - nebula-net

networks:
  nebula-net:
