
name: test client
on:
  push:
    branches: [master, dev, "release-**"]
  pull_request:
    branches: [master, dev, "release-**"]
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-client:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - large
    env:
      GOPROXY: ${{ vars.GOPROXY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.22.4
      - name: NebulaGo Unit tests
        run: make test
      - name: NebulaGo e2e tests
        run: |
          make e2e-up
          sleep 10
          make e2e
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out,./e2e.out
          fail_ci_if_error: true
          verbose: true
          
      - name: Teardown e2e
        if: always()
        run: make e2e-down
